g++ walle.cpp -g -o output

SAMPLE=
echo "$SAMPLE"
echo "expected: 1"
echo -n "actual: "
echo "$SAMPLE" | ./output | cat
echo

SAMPLE=E
echo "$SAMPLE"
echo "expected: 2"
echo -n "actual: "
echo "$SAMPLE" | ./output | cat
echo

SAMPLE=NOSE
echo "$SAMPLE"
echo "expected: 4"
echo -n "actual: "
echo "$SAMPLE" | ./output | cat
echo

SAMPLE=NSSEOOONNOEESN
echo "$SAMPLE"
echo "expected: 11"
echo -n "actual: "
echo "$SAMPLE" | ./output | cat
echo

SAMPLE=NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
echo "$SAMPLE"
echo "expected: 52"
echo -n "actual: "
echo "$SAMPLE" | ./output | cat
echo

SAMPLE=NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNSSSSSSSSSSSSSSSSSSSSSSSSSS
echo "$SAMPLE"
echo "expected: 621"
echo -n "actual: "
echo "$SAMPLE" | ./output | cat
echo

echo "Test for memory leaks (requires user input): "
valgrind --leak-check=yes ./output
